name: Run openrent searches

on:
  schedule:
    - cron: '0/20 7-23 * * *'
  workflow_dispatch:

jobs:

  run_searches:

    name: Run Openrent Searches and email results
    # env: 
    #   GMAIL_KENNY: ${{ secrets.GMAIL_KENNY }}
    #   GMAIL_KENNY_PASS: ${{ secrets.GMAIL_KENNY_PASS }}

    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps: 

      - name: Checkout
        uses: actions/checkout@v3

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: "projects/1012731031602/locations/global/workloadIdentityPools/gh-pool/providers/gh-provider"
          service_account: "github-actions-service-account@kenny-personal-projects.iam.gserviceaccount.com"


      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.12'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run searches and update completed listings 
        run: |
          python main.py
      
      - name: Commit and Push Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"